### ISSUE TITLE
[3.1.0] Chopping wood Bornholm 1.4 / Australia 2.0

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#347]
I have had no luck so far chopping trees with a hatchet on either of the above maps.

**Comment by ReDBaroN1** [comment]
Same for me with Bornholm 1.4.

Also, not getting any scrap or cinder when sledging a wreck or yellow brick pallet.

**Comment by RC-Robio** [comment]
Check to make sure you have updated to the latest description.ext. As all harvest-able objects like trees, bushes, and trash ect have been moved there.

**Comment by Ghostrider-DbD-** [comment]
I believe I am using the correct ones but will double check using a clean unmodified mission file.
Below is a dropbox link to a pbo with the two description.ext which have been renamed to be obvious which came from which mission file.
https://www.dropbox.com/s/khn5dsfb39vvjhx/ForRobio.pbo?dl=0

**Comment by RC-Robio** [comment]
Looks correct. Is it all trees, or just some of them?

**Comment by ReDBaroN1** [comment]
Of course description.ext updated. Works on my altis server although the yellow pallet of cinder drops scrap.. 

Can't harvest or sledge anything on bornholm that me and my players have found yet.

**Comment by Ghostrider-DbD-** [comment]
All trees I have tried on both Bornholm 1.4 and Australia 2.0. I unpacked brg_africa and tried adding what I thought were class names to the trees and bushes lists for Australia but that did not seem to help. I am checking with the default mission.pbo's now.

**Comment by ReDBaroN1** [comment]
I've already tried default pbo's. Still no luck.

**Comment by RC-Robio** [comment]
Change to:
Rocks[] = {
			"bo_r2_boulder1.p3d",
			"bo_r2_boulder2.p3d",
			"bo_r2_rock1.p3d",
			"bo_r2_rocktower.p3d",w
			"bo_r2_rockwall.p3d"
		};
		ATM[] = {
			"nastenka.p3d",
			"nastenka2.p3d",
			"nastenka3.p3d"
		};
		Water[] = {
			"misc_well.p3d",
			"misc_wellpump.p3d",
			"kasna_new.p3d"
		};
		Trash[] = {
			"p_pumpkin_summer.p3d",
			"pumpkin.p3d",
			"misc_postbox.p3d",
			"popelnice.p3d",
			"garbage_misc.p3d",
			"paletyc.p3d",
			"junkpile.p3d",
			"kontejner.p3d",
			"misc_chickencoop.p3d",
			"misc_boogieman.p3d",
			"misc_hutch.p3d",
			"garbage_paleta.p3d",
			"misc_cargo1a.p3d",
			"misc_cargo2a.p3d",
			"misc_greenhouse.p3d",
			"zastavka_stojan.p3d",
			"p_helianthus.p3d",
			"junkpile_f.p3d",
			"bricks_v2_f.p3d",
			"woodenbox_f.p3d"
		};
		Trees[] = {
			"bo_t_populus3s.p3d",
			"bo_t_fagus2w.p3d",
			"bo_t_betula2s.p3d",
			"bo_t_fagus2s.p3d",
			"bo_t_fagus2f.p3d",
			"bo_t_sorbus2s.p3d",
			"bo_t_fraxinus2w.p3d",
			"bo_t_salix2s.p3d",
			"bo_t_malus1s.p3d",
			"bo_t_betula1f.p3d",
			"bo_t_pinusn2s.p3d",
			"bo_t_picea2s.p3d",
			"bo_t_larix3s.p3d",
			"bo_t_picea3f.p3d",
			"bo_t_picea1s.p3d",
			"misc_fallentree2.p3d",
			"misc_stub2.p3d",
			"bo_t_fraxinus2s.p3d",
			"bo_t_quercus2f.p3d",
			"misc_trunk_water.p3d",
			"misc_trunk_torzo.p3d",
			"bo_t_alnus2s.p3d",
			"misc_fallentree1.p3d",
			"bo_t_betula2f.p3d",
			"bo_t_pinusn1s.p3d",
			"bo_t_pinuss2f.p3d",
			"bo_t_quercus3s.p3d",
			"bo_t_carpinus2s.p3d",
			"misc_fallenspruce.p3d",
			"bo_t_stub_picea.p3d",
			"misc_stub1.p3d",
			"bo_t_acer2s.p3d",
			"bo_t_betula2w.p3d",
			"bo_t_pyrus2s.p3d",
			"bo_b_corylus.p3d"
		};
		Bushes[] = {
			"bo_b_craet1.p3d",
			"bo_b_craet2.p3d",
			"bo_b_corylus.p3d",
			"bo_b_corylus2s.p3d",
			"bo_b_betulahumilis.p3d",
			"bo_b_sambucus.p3d",
			"bo_b_salix2s.p3d",
			"bo_b_canina2s.p3d",
			"bo_b_pmugo.p3d",
			"bo_b_prunus.p3d"
		};
		Wrecks[] = {
			"wall_fen1_5_pole.p3d",
			"wall_fen1_5_2.p3d",
			"wall_tin_4_2.p3d",
			"wall_fen1_5.p3d",
			"wall_indfnc_3.p3d",
			"wall_indfnc_9.p3d",
			"wall_indfnc_corner.p3d",
			"misc_concrete_high.p3d",
			"plot_vlnplech2.p3d",
			"misc_g_pipes.p3d",
			"wall_tincom_9.p3d",
			"wall_tin_4.p3d",
			"plot_vlnplech1.p3d",
			"wall_tincom_9_2.p3d",
			"wall_tincom_3.p3d",
			"wall_tincom_pole.p3d",
			"datsun01t.p3d",
			"datsun02t.p3d",
			"skodovka_wrecked.p3d",
			"lada_wrecked.p3d",
			"hiluxt.p3d",
			"uaz_wrecked.p3d",
			"ural_wrecked.p3d"
		};
	};
};

**Comment by RC-Robio** [comment]
The above is for Bornholm, as I do not have Australia downloaded.

**Comment by Ghostrider-DbD-** [comment]
That seems to have fixed the issue. Thank you for the rapid reply and solution.

**Comment by vbawol** [comment]
Fixed for 0.3.2, thanks to Robio!

**Comment by D0vev** [comment]
Sorry to annoy you. But I am still not able to do so :/

**Comment by RC-Robio** [comment]
It was updated on the experimental build here: https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/mpmissions/epoch.Bornholm/description.ext

**Comment by D0vev** [comment]
Thank you for your fast reply. Is there something else I need to update? My description.ext looks exact the same. Still no luck with wood or stone.
