### ISSUE TITLE
Major issue - safes can be looted even then locked (by anyone)

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#424]
Title says it all.

**Comment by RC-Robio** [comment]
This is also infistar related.

**Comment by infiSTAR** [comment]
I have nothing to do with that crap, what are you talking about?
Maybe some people updated their epoch servers and have somewhat old versions of the anti-hack which then changes / reverts functions? But nothing related to me :)

**Comment by Uranoxyd** [comment]
Its not infistar related, there is a syntax error in https://github.com/EpochModTeam/Epoch/blob/master/Sources/epoch_server_settings/configs/security/security_checks.h line 67 producing this error:

```
14:45:35 Error in expression < [2, 3] || (_this select 1) getVariable['EPOCH_Locked;, false])>
14:45:35   Error position: <'EPOCH_Locked;, false])>
14:45:35   Error Fehlendes '
```

**Comment by infiSTAR** [comment]
Oh, good to know Uranoxyd, I was just starting to look into it but apparently it is like every time.. people that don't know what they are talking about spreading the word until everybody assumes false truth and errors never get fixed. Good you posted this so it can actually be fixed :+1:

**Comment by infiSTAR** [comment]
What you posted there seems to be from that copy paste tool. There might be another issue with the safe locking as probably not everybody runs it

**Comment by RC-Robio** [comment]
That was my bad Chris. I do know what I am talking about. Didn't mean to jump the gun. I apologize.

**Comment by Uranoxyd** [comment]
maybe, i just searched the codebase for `'EPOCH_Locked;, false` and found this.

**Comment by MGTDB** [comment]
This is the error line in security_checks.h

InventoryOpened = "_this spawn EPOCH_initUI; (locked (_this select 1) in [2, 3] || (_this select 1) getVariable['EPOCH_Locked;, false])";

**Comment by infiSTAR** [comment]
no problem, sorry RC-Robio  for being rude. You would not believe how many people emailed me today about that problem ^^

**Comment by infiSTAR** [comment]
btw for those who don't see the issue here. it is in

epoch_server_settings\configs\security\security_checks.h

InventoryOpened = "_this spawn EPOCH_initUI; (locked (_this select 1) in [2, 3] || (_this select 1) getVariable['EPOCH_Locked;, false])";

there is a ; behind EPOCH_Locked instead of a single quote '

should be this instead
InventoryOpened = "_this spawn EPOCH_initUI; (locked (_this select 1) in [2, 3] || (_this select 1) getVariable['EPOCH_Locked', false])";

**Comment by RC-Robio** [comment]
Pull Request created:
https://github.com/EpochModTeam/Epoch/commit/c35974512f1f7eb035364e2fac8cf39f3a5593ee

**Comment by Skaronator** [comment]
fixed via https://github.com/EpochModTeam/Epoch/commit/34e8806c287acc8e5c30903c2d0b198475fbbf94

**Comment by Uranoxyd** [comment]
It seems the wrong PBO was packed after the patch. The change was made in `a3_epoch_server_settings` and in the last commit for the `Server_Install_Pack` `a3_epoch_server.pbo` was changed not `a3_epoch_server_settings.pbo`. So, the bug remains :)

**Comment by vbawol** [comment]
Sorry about that guys, repacked the settings pbo and pushed build 053 https://github.com/EpochModTeam/Epoch/releases
